### ISSUE TITLE
Make preferences page follow system light/dark mode

### ISSUE THREAD

**Issue by bragefuglseth** [abb128/LiveCaptions#13]
Currently, the preferences page for the application seems to be locked to dark mode. I suppose this is a conscious UI decision, but I don't see why it should be this way. The page doesn't display any media or any content that the user will concentrate on for longer periods of time.

I suggest making it follow the system light/dark preference by default.

(By the way, this is a really cool app!)

**Comment by abb128** [comment]
Windows other than the main window now follow system theme in ba9d6c4aabc370d4040078a8232bd22d6e2085c0
