### ISSUE TITLE
aprilv0 Benchmark Fail

### ISSUE THREAD

**Issue by niezywa** [abb128/LiveCaptions#15]
Slightly potato, but this would've been very useful for me so I hoped it could work :/. 
Hardware: (please provide your system specifications and hardware information)

* Lenovo ThinkPad X131e
* Intel(R) Core(TM) i3-2367M CPU @ 1.40GHz
* Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller
* 12GB RAM

Benchmark result: 0,88

**Comment by abb128** [comment]
The latest release (0.3+) has new functionality to run on weaker devices and lower benchmark requirements. Try running it again and let me know if it works now

**Comment by niezywa** [comment]
It does work :smile: ! It doesn't quite catch up, but it's perfectly usable, especially on the performance power profile with charger plugged in.

Thank you for your great work!
