### ISSUE TITLE
aprilv0 Benchmark Fail

### ISSUE THREAD

**Issue by dav23r** [abb128/LiveCaptions#21]
Hardware: (please provide your system specifications and hardware information)

Benchmark result: 0.79

![image](https://user-images.githubusercontent.com/11087478/208906483-e3fa8eab-a855-4af5-8ca2-3adc11dd01ab.png)

**Comment by abb128** [comment]
That processor seems like it should be capable enough, could it be thermal/power throttling or did you have any processing-intensive programs open during the benchmark?

**Comment by dav23r** [comment]
Hi @abb128,
Thanks for prompt reply. Yes, it were thermals/throttling. I plugged in power and the benchmark passed. Another (probably expected) observation: once plugged out of power during live captioning the speed started noticeably lag behind and accuracy would diminish - the helpful small warning sign was there though.
