### ISSUE TITLE
Hard to read tip in regards to always on top

### ISSUE THREAD

**Issue by Doomsdayrs** [abb128/LiveCaptions#24]
It's not easy to notice, easy to overlook

**Comment by abb128** [comment]
On X11, you can now automatically always keep it on top by enabling the switch in settings.

On Wayland, the tip is now customized to whether you're running KDE or GNOME and it should be more clear
![image](https://user-images.githubusercontent.com/65567823/213859934-ca0fe5ca-67b8-4da8-87de-16ac9eb1ab04.png)
