### ISSUE TITLE
aprilv0 Benchmark Fail

### ISSUE THREAD

**Issue by dav23r** [abb128/LiveCaptions#27]
Hardware: (please provide your system specifications and hardware information)

Benchmark result: 1,15

Fail on third gen laptop i5:
```
Intel® Core™ i5-3317U CPU @ 1.70GHz × 4
Mesa Intel® HD Graphics 4000 (IVB GT2)
Gnome Version 3.36.8
Windowing System Wayland
OS Name Linux Mint 20.1
```

**Comment by abb128** [comment]
The latest release (0.3+) has new functionality to run on weaker devices and lower benchmark requirements. Try running it again and let me know if it works now

**Comment by dav23r** [comment]
Now, I get scores of 1.11 and 1.15 under negligible load on the system and 0.8-0.9 under moderate load (yt video playing, scrolling through browser tabs).

**Comment by abb128** [comment]
That sounds about right for that hardware, but at least you should be able to get past the benchmark now right? Does it work well?

**Comment by dav23r** [comment]
Yes, I'm past the benchmark and can use live captions. It's quite usable, though with a bit more latency or errors than on my 3rd gen Ryzer5 series laptop.
