### ISSUE TITLE
Write output to file?

### ISSUE THREAD

**Issue by KCGD** [abb128/LiveCaptions#31]
A feature to write the output of this program to a file would be very nice (maybe with format options like plain text or srt?).
Is this feature possible?

**Comment by abb128** [comment]
There's now a button to export to text in the new history window
![image](https://user-images.githubusercontent.com/65567823/217669580-328c6c90-cdcb-499e-be3f-aa6c0f91aa9c.png)

**Comment by LavedenC1** [comment]
@abb128 button does nothing on hyprland/qs
