### ISSUE TITLE
aprilv0 Benchmark Fail

### ISSUE THREAD

**Issue by tagraf** [abb128/LiveCaptions#35]
Benchmark result: 0.83
Hardware:
##############################
$ neofetch --off
OS: Debian GNU/Linux 11 (bullseye) x86_64 
Kernel: 5.10.0-19-amd64 
Uptime: 35 days, 1 hour, 51 mins 
Packages: 3735 (dpkg), 7 (flatpak), 10 (snap) 
Shell: bash 5.1.4 
Resolution: 1920x1080, 1920x1080 
DE: GNOME 3.38.6 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD FX-8320 (8) @ 3.657GHz 
GPU: NVIDIA GeForce GTX 550 Ti 
Memory: 8255MiB / 15909MiB 

##############################
$ inxi -Fx
System:    Host: localhost Kernel: 5.10.0-19-amd64 x86_64 bits: 64 compiler: gcc v: 10.2.1 Desktop: GNOME 3.38.6 
           Distro: Debian GNU/Linux 11 (bullseye) 
Machine:   Type: Desktop Mobo: ASUSTeK model: SABERTOOTH 990FX R2.0 v: Rev 1.xx serial: <superuser required> 
           BIOS: American Megatrends v: 0803 date: 08/15/2012 
CPU:       Info: 8-Core model: AMD FX-8320 bits: 64 type: MCP arch: Bulldozer rev: 0 L2 cache: 2 MiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 56188 
           Speed: 3307 MHz min/max: N/A Core speeds (MHz): 1: 3307 2: 3823 3: 3123 4: 3589 5: 3608 6: 2878 7: 3047 
           8: 3661 
Graphics:  Device-1: NVIDIA GF116 [GeForce GTX 550 Ti] vendor: eVga.com. driver: nvidia v: 390.141 bus ID: 01:00.0 
           Display: x11 server: X.Org 1.20.11 driver: loaded: nvidia resolution: 1: 1920x1080~60Hz 
           2: 1920x1080~60Hz 
           OpenGL: renderer: llvmpipe (LLVM 11.0.1 256 bits) v: 4.5 Mesa 20.3.5 direct render: Yes 
Audio:     Device-1: Advanced Micro Devices [AMD/ATI] SBx00 Azalia vendor: ASUSTeK driver: snd_hda_intel v: kernel 
           bus ID: 00:14.2 
           Device-2: NVIDIA GF116 High Definition Audio vendor: eVga.com. driver: snd_hda_intel v: kernel 
           bus ID: 01:00.1 
           Device-3: Logitech HD Pro Webcam C920 type: USB driver: snd-usb-audio,uvcvideo bus ID: 8-2:4 
           Sound Server: ALSA v: k5.10.0-19-amd64 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: ASUSTeK P8 series driver: r8169 
           v: kernel port: b000 bus ID: 0a:00.0 
           IF: enp10s0 state: up speed: 1000 Mbps duplex: full mac: 30:85:a9:93:84:39 
           Device-2: Realtek RTL8188CUS 802.11n WLAN Adapter type: USB driver: rtl8192cu bus ID: 1-3:2 
           IF: wlxe84e061c26d5 state: down mac: 4e:4f:1c:0b:a5:8c 
           IF-ID-1: tun0 state: unknown speed: 10 Mbps duplex: full mac: N/A 
Drives:    Local Storage: total: 3.18 TiB used: 91.92 GiB (2.8%) 
           ID-1: /dev/sda vendor: Western Digital model: WDBNCE5000PNC size: 465.76 GiB temp: 26 C 
           ID-2: /dev/sdb vendor: Western Digital model: WD10EAVS-00D7B1 size: 931.51 GiB temp: 29 C 
           ID-3: /dev/sdc vendor: Samsung model: SSD 860 QVO 2TB size: 1.82 TiB 
Partition: ID-1: / size: 1.79 TiB used: 60.97 GiB (3.3%) fs: ext4 dev: /dev/sdc1 
Swap:      Alert: No Swap data was found. 
Sensors:   System Temperatures: cpu: 39.9 C mobo: N/A gpu: nvidia temp: 57 C 
           Fan Speeds (RPM): N/A gpu: nvidia fan: 30% 
Info:      Processes: 340 Uptime: 35d 2h 34m Memory: 15.54 GiB used: 8.16 GiB (52.6%) Init: systemd runlevel: 5 
           Compilers: gcc: 10.2.1 Packages: 3755 Shell: Bash v: 5.1.4 inxi: 3.3.01

**Comment by abb128** [comment]
The latest release (0.3+) has new functionality to run on weaker devices and lower benchmark requirements. Try running it again and let me know if it works now

**Comment by tagraf** [comment]
Ran it back up - current version: 0.3.1
It worked!
