### ISSUE TITLE
Obtaining hardware specification automatically (or gives user what to do in order to extract info)

### ISSUE THREAD

**Issue by tagraf** [abb128/LiveCaptions#36]
https://github.com/abb128/LiveCaptions/blob/aa3dda1b914493eefda3c31382e9baf7e23b72fe/src/livecaptions-welcome.c#L161

If time avail for a new project but consider this a low priority.

I would suggest you take advantage of 'uname', 'lscpu', 'inxi' or whichever commands, will extract any relevant info regarding the specification of hardware and then append that to the github's URL for adding comments to the issues.  I suppose the challenge is that some commands may not exist on certain OSes but consider it as an exception.
...OR...
Change the commentary by instructing the user to: "In order to get hardware info, please run this command then paste it here. 'inxi –Fx'

**Comment by abb128** [comment]
The new tracking issue (https://github.com/abb128/LiveCaptions/issues/40) makes note of the `inxi` command to help users figure out
