### ISSUE TITLE
History View

### ISSUE THREAD

**Issue by abb128** [abb128/LiveCaptions#4]
In some cases, it may be useful to have a history view with scrolling, text selection and copying

**Comment by abb128** [comment]
Mockup made by Martinez on the Discord

![image](https://user-images.githubusercontent.com/65567823/207047407-69fe1c67-0832-47ad-b4fa-5ec6626a11d4.png)

**Comment by Solarunit** [comment]
It also would be nice so save output text to the file.

**Comment by user82622** [comment]
Would be amazing to see :)

**Comment by abb128** [comment]
An initial history view has been implemented in the main branch. You can open it through settings for now.

![image](https://user-images.githubusercontent.com/65567823/217668435-5849a0ac-d862-40ab-a131-8ccae158fcd5.png)
![image](https://user-images.githubusercontent.com/65567823/217668656-b2205d6c-3ba6-4f9b-a9e4-876467bfc4c8.png)

You can export the entire history to text as well.
![image](https://user-images.githubusercontent.com/65567823/217668772-92188400-d316-4ade-a4e8-1241ce5d44b5.png)

If you have any issues or feature requests be sure to open a new issue
