### ISSUE TITLE
Enhancement: Add sort capabilities to the History Viewer

### ISSUE THREAD

**Issue by aproposnix** [abb128/LiveCaptions#43]
Right now, LiveCaptions is showing the newest entry at the bottom of the history. It would be nice to be able to have the newest entry on top. 

Great app btw. Thanks for developing it.

**Comment by abb128** [comment]
Usually human language is written from up to down. I think having new entries at the top would make a weird history where individual entries are written from up to down but the entries themselves are being sorted in reverse from down to up and everything chronologically is messed up. Is there any reason you'd prefer it that way?

**Comment by aproposnix** [comment]
TO be honest. I'm not sure what I was thinking at the time. Sorry for the the inconvenience. This can be closed. If I remember what I was thinking, I'll open a separate request with more detailed explanation.
