### ISSUE TITLE
select text to translate

### ISSUE THREAD

**Issue by antonio24073** [abb128/LiveCaptions#46]
Hi friend,

please, there is a way to let select the text with cursor? I'm using it to transcribe in english but there are some words that I need to translate with gnome screen word translate.

https://extensions.gnome.org/extension/1849/screen-word-translate/

thank you for your efforts.. that's a great friend

**Comment by antonio24073** [comment]
Or put an update button on live captions history, maybe this approach is better

**Comment by abb128** [comment]
I added a refresh button to history in b7a0aaffa1f981a541518b39e33c912b60c8d9e2
![image](https://user-images.githubusercontent.com/65567823/229223651-1bc34e78-5e19-4449-bc39-fb39bdd7a1c5.png)

**Comment by antonio24073** [comment]
I will wait the package update. Thank you.
