### ISSUE TITLE
Configurable border width

### ISSUE THREAD

**Issue by miloslavnosek** [abb128/LiveCaptions#64]
The default border width for the caption window seems too large. I would welcome a possibility to be able to configure it.

**Comment by abb128** [comment]
The border width is 1 pixel at 100% scaling, it was added due to https://github.com/abb128/LiveCaptions/issues/9. I think a setting for this would be too minor and would just add to settings menu bloat

**Comment by whitequark** [comment]
The border looks like this for me, not sure why:

![Screenshot_20230531_103325](https://github.com/abb128/LiveCaptions/assets/54771/0b0bbb2a-b911-4a78-a6e1-2a2033b05bb6)

That's a lot more than (scaling factor) pixels, which should be at most 2 for me.

**Comment by miloslavnosek** [comment]
> The border looks like this for me, not sure why:
> 
> ![Screenshot_20230531_103325](https://user-images.githubusercontent.com/54771/242245950-0b0bbb2a-b911-4a78-a6e1-2a2033b05bb6.png)
> 
> That's a lot more than (scaling factor) pixels, which should be at most 2 for me.

That's exactly how it looks for me too. I was under the impression that this was by design.
    
I'm not sure what could be causing it. I'm on i3wm, and I'm just using the flatpak version 0.4.0.

**Comment by whitequark** [comment]
> I'm on i3wm, and I'm just using the flatpak version 0.4.0.

Same setup here.

**Comment by abb128** [comment]
This seems to be the solid-csd class that GTK adds when it determines the compositor doesn't support window shadows. It's normally supposed to look like this.
![image](https://github.com/abb128/LiveCaptions/assets/65567823/87ffa941-2dd0-4960-bcde-a7689ffed2f8)

I can't seem to affect solid-csd by defining my own styles for .solid-csd in style.css but putting `gtk_widget_remove_css_class(GTK_WIDGET(self), "solid-csd");` in livecaptions-window initializer seems to be an ugly fix

**Comment by abb128** [comment]
I added the fix to 3b0a8c85cafcf9e32c6e33214b8bd54491f63740 since I couldn't find a better workaround

**Comment by whitequark** [comment]
This addresses the issue for me, thanks!
