### ISSUE TITLE
[no-gui] Perhaps to have unix text-based option?

### ISSUE THREAD

**Issue by dreamcat4** [abb128/LiveCaptions#74]
Hi!,
This feature, after some consideration might be of a considered value in specific mobile only use cases. For example: universal translator. Whereby the intended platform or device would not rely so heavily upon requiring xorg/wayland. But instead help to be usable in other mobile friendly situations (which may have alternative GUI schemes).

The use case would also be something of a value to help accessibility or usability in mind (under adverse conditions, including people with disabilities and/or in hostile environments where those assumptions of GUI tend to get thrown out).

I am not sure how feasible this is. But it's generally supposed to being proposed as a generic proposal for new feature support. And without being tied too deeply into any specific assumtions about individual use cases. (although may indeed have some broad variety of valid real world usecase, more than only 1-2).

**Comment by abb128** [comment]
There is an example application at https://github.com/abb128/april-asr/blob/main/example.cpp that supports piping in PCM16 input and outputs results to stdout. Maybe you can use that as a starting off point

**Comment by dreamcat4** [comment]
thank you so much @abb128! very kind to point me in the right direction. most helpful and to close the item here on this project being something more distant.

i suppose we could still have the question if this sort of functionality would be of interest or benefit (to livecaptions project, as a different launch mode). but that then is more for how code and functionality is indeed shared or reproduced across differing projects, and also which other common or required libraries ends up getting pulled in (or not! as the case may be)

anyhow please feel free to close as being resolved (answered question), if indeed nothing else is left remaining actionable or applicable here. it was indeed most appreciated for the link, br.

**Comment by abb128** [comment]
This project is mainly focused on the desktop GUI experience so I will be closing this issue
