### ISSUE TITLE
Visual style of window (minor)

### ISSUE THREAD

**Issue by kdwk** [abb128/LiveCaptions#9]
For libadwaita windows in dark mode, there is usually a subtle light grey border that distinguishes the window if it is on a dark background. This helps to reduce cognitive load for users because they can easily tell where the window starts and ends. However, if my eyes are correctly ;) , there doesn't seem to be such a border around the window.

**Comment by mossymossmoss** [comment]
I believe there is, just that the pure black background makes it hard to distinguish. It may be good to have to option to toggle between default Adwaita colors and the black background 
![Border](https://user-images.githubusercontent.com/56167669/208092712-3958a553-3074-4f41-abea-c750f2655a80.png)

**Comment by abb128** [comment]
The black background is achieved by using the osd class. The default colors have a more visible border but I think the low contrast makes it much less readable
![image](https://user-images.githubusercontent.com/65567823/208221113-8f24043c-c1dd-4cb9-9aed-bb81afd14f87.png)

**Comment by abb128** [comment]
Added a more visible border in ba9d6c4aabc370d4040078a8232bd22d6e2085c0
![image](https://user-images.githubusercontent.com/65567823/208279853-f198d871-1f89-4581-867d-b44fa4ee0e31.png)
