### ISSUE TITLE
Issues on first look and a suggestion

### ISSUE THREAD

**Issue by Thekiller2498** [abb128/LiveCaptions#91]
Typing this comment on ur keyboard rn, it genuinely looks better than google, im using the eng -74 model for the v2t and its is amazing.

My issues so far are:
My swipe types are very inaccurate and it seems to not have ai predicting the words i wanted to say.
Seems lime the same lack of good ai in typing is also causing the 3 top typing suggestions to be off until lile 80℅ of the word is written.

Another thing is that all my text highlights for spell check while im typing for some for some reason, i dont think this hapoened b4.

Google also has a feature where when your on the symbols keyboard, and you type a symbol it auto switches back to normal. Its usefull because normally i dont type more than one symbol at a time. Would be nice to. have it as a setting.

Another thing is when i do type a typo and click to edit the word, it automatically puts me to the end of that word even if i tapped in the middle.

You should also add automatic capitalizations of the letter I. And put for the 3 main suggestions, put the best one the the middle rather than on the side.

Also wanted to add one thing, if your going to add this for windows aswell, do you think you can add on snapdrop.net/pairdrop.net integrations. This is an opensource software that I find better than apples airdrop and use very often. Whether it works or not is a bit iffy but having a cross device clipboard would be really nice. Where I can copy and paste text, images and even files between devices via a clipboard manager or something.

**Comment by abb128** [comment]
Thanks for the feedback! FYI this repo is for the live captions program for Linux, a project distinct from the FUTO Keyboard
