### ISSUE TITLE
REQUEST: Add/change the numeric layout to a Numpad Keyboard one.

### ISSUE THREAD

**Issue by CyberCimmerian** [abb128/LiveCaptions#92]
Hi there.

I just wanted to request an option to change/add a Numpad Layout (like the one on a PC keyboard), instead of a number row.
So it would be something like:

789
456
123
  0

Thank you.

**Comment by abb128** [comment]
This is the wrong repo, looks like you already posted it to the correct one https://github.com/futo-org/android-keyboard/issues/64
