### ISSUE TITLE
Fails to build on arch, via AUR

### ISSUE THREAD

**Issue by fyrezard** [abb128/LiveCaptions#98]
Hello, I tried installing this from [the AUR](https://aur.archlinux.org/packages/livecaptions) but it fails to build as per the latest comments on there.

You don't seem to check it frequently, so I've opened a new issue on here to notify you.

**Comment by abb128** [comment]
Does it work if you install libpulse and openmpi? If not could you share the build error, because it builds on my machine

**Comment by fyrezard** [comment]
> Does it work if you install libpulse and openmpi? If not could you share the build error, because it builds on my machine

Turns out I needed openmpi which wasn't installed.  Thank you, closing this issue

**Comment by abb128** [comment]
I'll add the two dependencies then
